DROP DATABASE IF EXISTS cmsDB;

CREATE DATABASE cmsDB;

USE cmsDB;

DROP TABLE IF EXISTS department, role, employee;

CREATE TABLE department (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE role (
id int AUTO_INCREMENT,
title VARCHAR(30) NOT NULL,
salary DECIMAL NOT NULL,
department_id INT,
PRIMARY KEY (id),
);

CREATE TABLE employee (
id int NOY NULL AUTO_INCREMENT,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INT NOT NULL,
manager_id INT,
PRIMARY KEY (id),
);
